version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: corlink
      POSTGRES_PASSWORD: corlink
      POSTGRES_DB: corlink
    volumes:
      - ./db:/var/lib/postgresql/data
  
  corlink-server:
    image: corlink-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    #do not start the server until the database is ready
    depends_on:
      - postgres 
    ports:
      - 8080:8080
    environment:
      ADMIN_KEY: changeme
      # don't change the below
      DB_HOST: postgres
      DB_USER: corlink
      DB_PASS: corlink
      DB_NAME: corlink
      DB_PORT: 5432
