version: "3"

services:
  corlink-bot:
    image: corlink-bot:latest
    container_name: corlink-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      DISCORD_TOKEN: changeme
      GUILD_ID: 123456789012345678
      LICENSING_SERVER_URL: http://changeme.com
      LICENSING_SERVER_KEY: changeme
      OWNER_ID: changeme
