name: Publish NPM Packages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  express:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: cd packages/express && npm install 
      - name: Build
        run: cd packages/express && npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: cd packages/express && npm publish --access public
  fastify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: cd packages/fastify && npm install 
      - name: Build
        run: cd packages/fastify && npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: cd packages/fastify && npm publish --access public
  node-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: cd packages/sdk/node && npm install 
      - name: Build
        run: cd packages/sdk/node && npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: cd packages/sdk/node && npm publish --access public
  browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: cd packages/sdk/browser && npm install 
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: cd packages/sdk/browser && npm publish --access public
