name: Publish NPM Packages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  express:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: CD into the directory
        run: cd packages/express
        id: cd
      - name: Install Dependencies 
        run: npm install 
      - name: Build
        run: npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: npm publish --access public
  fastify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: packages/fastify
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: npm install 
      - name: Build
        run: npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: npm publish --access public
  node-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: packages/sdk/node
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies 
        run: npm install 
      - name: Build
        run: npm run compile
      - name: Setup User 
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - name: Publish
        run: npm publish --access public
